{% set version = "0.9.0" %}

package:
  name: nginx-language-server
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/nginx-language-server/nginx_language_server-{{ version }}.tar.gz
  sha256: 8066b8e0a450bcaa625b9bc692c938d8e547377c1b8eb2e8ef070f2c2f974106

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - nginx-language-server = nginx_language_server.cli:cli

requirements:
  host:
    - python ={{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - crossplane >=0.5.8,<0.6.0
    - lsprotocol >=2022.0.0a10
    - pydantic >=1.7.3,<2.0.0
    - pygls >=1.0.0,<2.0.0

test:
  commands:
    - pip check
    - nginx-language-server --help
  imports:
    - nginx_language_server
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/pappasam/nginx-language-server
  summary: A language server for nginx.conf
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
